#!/bin/bash
## Move this file to /usr/sbin/roslaunch
#source ~/catkin_ws/devel/setup.bash
source /etc/ros/env.sh
export ROS_HOME=$(echo ~ubuntu/.ros
roslaunch rosbridge_server rosbridge_websocket.launch &
PID=$!
wait “$PID”